
import Navbar from '@/Share/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import GlobalState from '@/Contaxt'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Jewelry shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar></Navbar>
          <div className=' pt-[75px]'>
            {children}
          </div>
        </GlobalState>

      </body>
    </html>
  )
}
