
import Navbar from '@/Share/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Jewelry shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div className=' mt-[75px]'>
          {children}
        </div>
      </body>
    </html>
  )
}
